apiVersion: apps/v1
kind: Deployment
metadata:
  name: beemylawyer-deployment
  labels:
    app: beemylawyer
spec:
  selector:
    matchLabels:
      app: beemylawyer
  replicas: 1
  template:
    metadata:
      labels:
        app: beemylawyer
    spec:
      containers:
        - name: beemylawyer
          image: "decorjim/beemylawyer-docker"
          ports:
            - containerPort: 8080
